### ISSUE TITLE
Transparent Skin

### ISSUE THREAD

**Issue by TheIdiot0** [X0nk/Bliss-Shader#180] opened 2024-06-11 21:38 UTC
AHH! Im a Ghost!
My skin is transparent... thats really it.
Vanilla:
![image](https://github.com/X0nk/Bliss-Shader/assets/114532380/fc748e76-d38c-44a6-8585-bc2202870355)
Bliss:
![image](https://github.com/X0nk/Bliss-Shader/assets/114532380/edb0b920-7cbc-48ad-a706-4ac8d737b490)

**Comment by X0nk** [comment] 2024-06-11 22:02
this is caused by my blending type for translucent entities. it only renders the front most part. i can change this. i only did that because it looked good on slimes.... i didnt think about player skins.

**Comment by X0nk** [comment] 2024-06-13 00:59
this should be fixed now, go re-download.

**Closed by X0nk** 2024-06-13 00:59 UTC

**Comment by TheIdiot0** [comment] 2024-07-13 13:23
thx
